LIBRERIA = lib
RECURSOS = $(LIBRERIA)/registros.c $(LIBRERIA)/instrucciones.c $(LIBRERIA)/memoria.c $(LIBRERIA)/buffer.c 
PRINCIPAL = main.c
SALIDA = laboratorio2

all: compilar ejecutar

compilar:
	gcc $(PRINCIPAL) $(RECURSOS) -o $(SALIDA)

ejecutar: 
	./$(SALIDA)
